#!/usr/bin/env bash
# One-shot devcontainer bootstrap: installs Postgres, creates the chase
# role+database, writes connection env to api/.env, and runs the existing
# web/api scaffolding.
set -euo pipefail

mkdir -p .debug/data

# --- Install & start Postgres ---------------------------------------------
if ! command -v psql >/dev/null 2>&1; then
  echo "Installing PostgreSQL..."
  sudo apt-get update
  sudo DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
    postgresql postgresql-contrib
fi

sudo service postgresql start

# --- Provision chase role + database --------------------------------------
PG_USER="chase"
PG_PASS="chase"
PG_DB="chase"

# sudoers in the MS devcontainer images grants passwordless root only, so we
# pipe SQL into psql running as the postgres unix user (peer auth) via root.
psql_postgres() {
  sudo su -l postgres -c "psql -tA $*"
}

if ! psql_postgres -c "\"SELECT 1 FROM pg_roles WHERE rolname='${PG_USER}'\"" | grep -q 1; then
  sudo su -l postgres -c "psql -v ON_ERROR_STOP=1" <<SQL
CREATE ROLE ${PG_USER} WITH LOGIN PASSWORD '${PG_PASS}' CREATEDB;
SQL
fi

if ! psql_postgres -c "\"SELECT 1 FROM pg_database WHERE datname='${PG_DB}'\"" | grep -q 1; then
  sudo su -l postgres -c "createdb -O ${PG_USER} ${PG_DB}"
fi

# --- Seed api/.env (only if missing or no PG vars yet) --------------------
ENV_FILE="api/.env"
touch "${ENV_FILE}"
if ! grep -q '^PGHOST=' "${ENV_FILE}"; then
  cat >> "${ENV_FILE}" <<EOF

# Auto-generated by .devcontainer/setup.sh
PGHOST=localhost
PGPORT=5432
PGUSER=${PG_USER}
PGPASSWORD=${PG_PASS}
PGDATABASE=${PG_DB}
PGSSLMODE=disable
EOF
fi

# --- Frontend deps --------------------------------------------------------
(cd web && npm install)

echo "Devcontainer ready: postgres://${PG_USER}@localhost:5432/${PG_DB}"
