{{- range $key, $value := .Values }}
{{- if $value.ingress }}
{{- with $value.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $key }}-ingress
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .ingressClassName }}
  ingressClassName: {{ .ingressClassName }}
  {{- end }}
  tls:
  - hosts:
    - {{ .host }}
    secretName: {{ $key }}-tls-secret
  rules:
  - host: {{ .host }}
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            {{- with (first $value.services) }}
            name: {{ .name }}
            port:
              number: {{ .port }}
            {{- end }}
{{- end }}
{{- end }}
{{- end }}