{{- if .Values.chase.auth.generateSecretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: chase-api-secret
  labels:
    app: {{ .Release.Name }}
type: Opaque
data:
  # Generate a random secret key using a Helm function
  secretKey: {{ randAlphaNum 35 | b64enc | quote }}
{{- end }}
